# Generated by Django 5.1.4 on 2024-12-05 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('positive', 'Положительный'), ('negative', 'Отрицательный')], max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='race',
            name='result',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='race',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race'),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
