# Generated by Django 5.1.4 on 2024-12-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_alter_registration_participant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='participant',
            new_name='user',
        ),
    ]
