# Generated by Django 5.1.4 on 2024-12-05 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_alter_race_result_alter_race_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('race', 'user')},
        ),
    ]
